// Re:Lefela — 📼 Tiro 1: SECL121 Assignment 1, word for word. HAND-AUTHORED from
// toolkit/ass1-mapping.json (FINAL, ear-checked by Megan 2026-09-11) and, for the second
// voice and the new phrase set, toolkit/ass1-mapping-v2.json (ear-checked 2026-09-12).
// Not generated by the app's build steps: the mappings are the record of what she
// listened to and approved, and every string below is copied out of one of them verbatim.
// ─────────────────────────────────────────────────────────────────────────────────────
// SOURCES. `zerwick-ass1-2026` = the Assignment 1 .docx (his word list, his intro lines,
// his glosses); `zerwick-story-af-2026` = his "Phakwe le mokoko +Afrikaans" story .docx
// (the sentence-level Afrikaans that anchors every story gloss); `zerwick-2024` = his
// Sound-values handout; plus `smart-guide-2026`, `pc` (Peace Corps), `app` (an existing
// Re:Lefela card), `autshumato`, `afwn`. Nothing here is invented Setswana.
//
// HIS SPELLINGS STAND. rêka, ôtla, Rapôô, yô, mašwi exactly as he printed them. His
// handout writes yôô / yôlê where the assignment writes yoo / yole — noted on the cards,
// not tidied (the Lediri precedent). `ôtla` shows his ASSIGNMENT gloss (feed) with a note
// that his own 2024 handout and the dictionary say punish; that question is on his list.
// yoo and yole get no gloss at all, because he glosses only yô — so those two, plus the
// two surnames, are readOnly: read-aloud cards, never quizzed on a meaning nobody wrote.
//
// THE VOICE — TWO OF THEM. `audio` is the first speaker (four WhatsApp voice notes,
// 2026-09-11); `audio2` is a SECOND speaker who read the same script onto five tapes,
// sliced and ear-checked 2026-09-12 (toolkit/ass1-mapping-v2.json, 48 clips, cut verbatim
// the same way). The tab has a V1/V2 toggle; either field may be missing, and the tab's
// resolver falls back to the other voice rather than going silent.
// ⚠️ NEITHER speaker is EVER named in this repo — it is public. The raw tapes live in
// gitignored corpus/audio/ass1/ and never enter git; only the cut clips ship.
//   · a1w-17 (yô) has NO `audio`: the first speaker's take is clipped at source (mic
//     overload measured through the vowel) and the declip rescue was rejected by her ear.
//     It used to ship silent. The second speaker's take was ear-checked and kept, so the
//     card now has `audio2` and this one word plays V2 in both modes.
//   · Five intro lines reuse audio the app ALREADY ships. a1i-02/03/06 point straight at
//     the live lesson clips; a1i-04/05 point at name-free cuts of u1l2-01 / u1l2-03,
//     copied in under their own ids, so no name — hers or a speaker's — is ever spoken.
//     Their `audio2` is the second speaker reading the same line off her own tape.
//   · a1i-07 stops after "wa". The speaker read SECL 121 in Setswana; the lecturer wants
//     it in ENGLISH, so Megan says "SECL 121" herself after the clip. Never re-extend it.
//   · WHOLE-STORY. The first speaker's tape holds ONE reading, slow (her ruling
//     2026-09-11) — that has not changed and never will. The second speaker recorded a
//     natural-pace read-through as well, so `whole.nat` exists with `audio2` only.
//
// NO SRS WRITES. Progress lives in device-local rl_ass1, XP rides as kind 'ass1'. Same
// rule as Warm-up, Medumo, Lediri and the rest: these assignment cards must not flood the
// review queue this app spent two sessions unblocking.
//
// TEMPORARY BY DESIGN. The assignment is due 14 September 2026. Afterwards the tab parks
// behind ?ass1=1 (the gym precedent) — parked, never deleted.

const RL_ASS1 = {
  /* 23 words, the assignment's own order, his glosses and his sound families. */
  words: [
    {id: 'a1w-01', tsw: 'rata', eng: 'like / love', af: 'lief wees', sound: 'a', src: ['zerwick-ass1-2026', 'zerwick-2024'], audio: 'items/a1w-01.mp3', audio2: 'items/a1w-01-v2.mp3', note: ''},
    {id: 'a1w-02', tsw: 'rêka', eng: 'buy', af: 'koop', sound: 'ê', src: ['zerwick-ass1-2026', 'zerwick-2024'], audio: 'items/a1w-02.mp3', audio2: 'items/a1w-02-v2.mp3', note: ''},
    {id: 'a1w-03', tsw: 'ôtla', eng: 'feed', af: 'voer', sound: 'ô', src: ['zerwick-ass1-2026'], audio: 'items/a1w-03.mp3', audio2: 'items/a1w-03-v2.mp3', note: 'his 2024 handout (Medumo md02) glosses ôtla = punish, and the dictionary agrees with punish. His two documents disagree; ask him. Pronunciation is what is marked.'},
    {id: 'a1w-04', tsw: 'loma', eng: 'bite', af: 'byt', sound: 'o', src: ['zerwick-ass1-2026', 'afwn'], audio: 'items/a1w-04.mp3', audio2: 'items/a1w-04-v2.mp3', note: ''},
    {id: 'a1w-05', tsw: 'lema', eng: 'plough', af: 'ploeg', sound: 'e', src: ['zerwick-ass1-2026'], audio: 'items/a1w-05.mp3', audio2: 'items/a1w-05-v2.mp3', note: ''},
    {id: 'a1w-06', tsw: 'ruruga', eng: 'swell', af: 'swel', sound: 'u', src: ['zerwick-ass1-2026', 'afwn'], audio: 'items/a1w-06.mp3', audio2: 'items/a1w-06-v2.mp3', note: ''},
    {id: 'a1w-07', tsw: 'modiri', eng: 'worker', af: 'werker', sound: 'i', src: ['zerwick-ass1-2026'], audio: 'items/a1w-07.mp3', audio2: 'items/a1w-07-v2.mp3', note: ''},
    {id: 'a1w-08', tsw: 'Mokoena', eng: '(a surname)', af: '(\'n van)', sound: 'oe', src: ['zerwick-ass1-2026'], audio: 'items/a1w-08.mp3', audio2: 'items/a1w-08-v2.mp3', note: 'a name: stays a name, no gloss to learn', readOnly: true},
    {id: 'a1w-09', tsw: 'tsie', eng: 'locust', af: 'springkaan', sound: 'ie', src: ['zerwick-ass1-2026', 'zerwick-2024'], audio: 'items/a1w-09.mp3', audio2: 'items/a1w-09-v2.mp3', note: 'handout: pronounced [tsi-ê]'},
    {id: 'a1w-10', tsw: 'Rapôô', eng: '(a surname)', af: '(\'n van)', sound: 'ôô', src: ['zerwick-ass1-2026'], audio: 'items/a1w-10.mp3', audio2: 'items/a1w-10-v2.mp3', note: 'a name; the long ô', readOnly: true},
    {id: 'a1w-11', tsw: 'llere', eng: 'ladder', af: 'leer', sound: 'l-lere', src: ['zerwick-ass1-2026', 'zerwick-2024', 'afwn'], audio: 'items/a1w-11.mp3', audio2: 'items/a1w-11-v2.mp3', note: 'syllabic l: the first l is a beat on its own (his handout)'},
    {id: 'a1w-12', tsw: 'monna', eng: 'man', af: 'man', sound: 'mo-n-na', src: ['zerwick-ass1-2026', 'zerwick-2024'], audio: 'items/a1w-12.mp3', audio2: 'items/a1w-12-v2.mp3', note: 'syllabic n (his handout)'},
    {id: 'a1w-13', tsw: 'rre', eng: 'father', af: 'pa', sound: 'r-re', src: ['zerwick-ass1-2026', 'zerwick-2024'], audio: 'items/a1w-13.mp3', audio2: 'items/a1w-13-v2.mp3', note: 'syllabic r (his handout writes rra > r-ra)'},
    {id: 'a1w-14', tsw: 'jwala', eng: 'plant (sow)', af: 'plant', sound: 'j', src: ['zerwick-ass1-2026', 'pc'], audio: 'items/a1w-14.mp3', audio2: 'items/a1w-14-v2.mp3', note: 'Peace Corps: jwala = sow'},
    {id: 'a1w-15', tsw: 'mašwi', eng: 'milk', af: 'melk', sound: 'š', src: ['zerwick-ass1-2026', 'zerwick-2024', 'afwn'], audio: 'items/a1w-15.mp3', audio2: 'items/a1w-15-v2.mp3', note: ''},
    {id: 'a1w-16', tsw: 'wena', eng: 'you', af: 'jy', sound: 'w', src: ['zerwick-ass1-2026', 'app'], audio: 'items/a1w-16.mp3', audio2: 'items/a1w-16-v2.mp3', note: 'already an app word (u1l1-18)'},
    {id: 'a1w-17', tsw: 'yô', eng: 'this (man)', af: 'hierdie man', sound: 'y', src: ['zerwick-ass1-2026', 'zerwick-2024'], audio2: 'items/a1w-17-v2.mp3', note: 'his handout: yô = this \'man\', like the yo in \'your\' · the first speaker\'s take is clipped at source (the mic overloaded straight through the vowel), so this one word plays the second speaker whichever voice you pick'},
    {id: 'a1w-18', tsw: 'yoo', eng: '(listed with yô, no separate gloss from him)', af: '', sound: 'y', src: ['zerwick-ass1-2026', 'zerwick-2024'], audio: 'items/a1w-18.mp3', audio2: 'items/a1w-18-v2.mp3', note: 'handout writes yôô; read-aloud card, gloss not invented', readOnly: true},
    {id: 'a1w-19', tsw: 'yole', eng: '(listed with yô, no separate gloss from him)', af: '', sound: 'y', src: ['zerwick-ass1-2026', 'zerwick-2024'], audio: 'items/a1w-19.mp3', audio2: 'items/a1w-19-v2.mp3', note: 'handout writes yôlê; read-aloud card, gloss not invented', readOnly: true},
    {id: 'a1w-20', tsw: 'khudu', eng: 'tortoise', af: 'skilpad', sound: 'kh', src: ['zerwick-ass1-2026', 'afwn'], audio: 'items/a1w-20.mp3', audio2: 'items/a1w-20-v2.mp3', note: ''},
    {id: 'a1w-21', tsw: 'ngaka', eng: 'doctor', af: 'dokter', sound: 'ng', src: ['zerwick-ass1-2026'], audio: 'items/a1w-21.mp3', audio2: 'items/a1w-21-v2.mp3', note: ''},
    {id: 'a1w-22', tsw: 'nyala', eng: 'marry', af: 'trou', sound: 'ny', src: ['zerwick-ass1-2026'], audio: 'items/a1w-22.mp3', audio2: 'items/a1w-22-v2.mp3', note: ''},
    {id: 'a1w-23', tsw: 'phiri', eng: 'wolf', af: '(wolf)', sound: 'ph', src: ['zerwick-ass1-2026', 'app', 'afwn'], audio: 'items/a1w-23.mp3', audio2: 'items/a1w-23-v2.mp3', note: 'app card u5l2-02 says wolf / hyena'},
  ],

  /* 8 read-along lines, the assignment's order — this IS the intro she says on camera. */
  intro: [
    {id: 'a1i-01', tsw: 'A re bueng!', eng: 'Let\'s talk!', af: 'Kom ons praat!', src: ['zerwick-ass1-2026'], audio: 'items/a1i-01.mp3', audio2: 'items/a1i-01-v2.mp3', note: ''},
    {id: 'a1i-02', tsw: 'Leina la gago ke mang?', eng: 'What is your name?', af: 'Wat is jou naam?', src: ['zerwick-ass1-2026'], audio: 'items/u1l2-02.mp3', audio2: 'items/a1i-02-v2.mp3', note: ''},
    {id: 'a1i-03', tsw: 'Dumela rra.', eng: 'Good day sir', af: 'Goeie dag meneer', src: ['zerwick-ass1-2026'], audio: 'items/u1l1-01.mp3', audio2: 'items/a1i-03-v2.mp3', note: ''},
    {id: 'a1i-04', tsw: 'Leina la me ke ...', eng: 'My name is ...', af: 'My naam is ...', src: ['zerwick-ass1-2026'], audio: 'items/a1i-04.mp3', audio2: 'items/a1i-04-v2.mp3', note: 'the clip is a name-free cut of the app\'s own line — say your name yourself'},
    {id: 'a1i-05', tsw: 'Sefane sa me ke ...', eng: 'My surname is ...', af: 'My van is ...', src: ['zerwick-ass1-2026'], audio: 'items/a1i-05.mp3', audio2: 'items/a1i-05-v2.mp3', note: 'the clip is a name-free cut of the app\'s own line — say your surname yourself'},
    {id: 'a1i-06', tsw: 'Ke ithuta Setswana.', eng: 'I am learning Setswana', af: 'Ek leer Setswana', src: ['zerwick-ass1-2026'], audio: 'items/u1l2-09.mp3', audio2: 'items/a1i-06-v2.mp3', note: ''},
    {id: 'a1i-07', tsw: 'Ke dira mmojulu wa SECL 121.', eng: 'I am doing Module SECL 121', af: 'Ek doen Module SECL 121', src: ['zerwick-ass1-2026'], audio: 'items/a1i-07.mp3', audio2: 'items/a1i-07-v2.mp3', note: 'the clip stops after "wa": the lecturer wants SECL 121 said in ENGLISH, so say "SECL 121" yourself right after the clip'},
    {id: 'a1i-08', tsw: 'Se ke kgatiso ya Tiro nomoro ya ngwe.', eng: 'This is Recording of Assignment No.1', af: 'Hierdie is Opname van Opdrag No.1', src: ['zerwick-ass1-2026'], audio: 'items/a1i-08.mp3', audio2: 'items/a1i-08-v2.mp3', note: 'the last line of the intro'},
  ],

  /* The story, 8 sentence cards from the slow reading. Each is drawn as its teaching
     chunks ("o ne a tsamaya" is one chunk), and every chunk lists its words one by one
     so the round teaches what each word is doing. Chunks join back to the sentence. */
  story: [
    {id: 'a1s-00', tsw: 'Phakwe le Mokoko',
     eng: 'The Hawk and the Rooster',
     af: 'Valk en Hoenderhaan',
     src: ['zerwick-ass1-2026', 'zerwick-story-af-2026'], audio: 'items/a1s-00.mp3', audio2: 'items/a1s-00-v2.mp3', note: '',
     chunks: [
       {tsw: 'Phakwe', eng: 'Hawk (Valk)',
        words: [{w: 'Phakwe', g: 'hawk; his Afrikaans: Valk'}],
        src: ['zerwick-story-af-2026'], note: ''},
       {tsw: 'le', eng: 'and / with',
        words: [{w: 'le', g: 'and, with'}],
        src: ['pc', 'app'], note: ''},
       {tsw: 'Mokoko', eng: 'Rooster (Hoenderhaan)',
        words: [{w: 'Mokoko', g: 'rooster, cock'}],
        src: ['zerwick-story-af-2026', 'afwn'], note: ''},
     ]},
    {id: 'a1s-01', tsw: 'Ga twe bogologolo Phakwe le Mokoko e ne e le ditsala tse dikgolo.',
     eng: 'It is said that long ago Hawk and Rooster were great friends.',
     af: 'Daar word vertel dat Valk en Hoenderhaan lank gelede goeie vriende was.',
     src: ['zerwick-ass1-2026', 'zerwick-story-af-2026'], audio: 'items/a1s-01.mp3', audio2: 'items/a1s-01-v2.mp3', note: '',
     chunks: [
       {tsw: 'Ga twe', eng: 'it is said',
        words: [{w: 'ga', g: 'here part of the fixed \'it is said\', not the usual \'not\''}, {w: 'twe', g: 'be said'}],
        src: ['zerwick-story-af-2026', 'autshumato'], note: 'Autshumato: \'Gantsi ga twe\' = \'It is often said\''},
       {tsw: 'bogologolo', eng: 'long ago',
        words: [{w: 'bogologolo', g: 'long ago, the olden days'}],
        src: ['zerwick-story-af-2026', 'smart-guide-2026', 'autshumato'], note: 'Smart Guide time-words list; his Afrikaans: lank gelede'},
       {tsw: 'Phakwe le Mokoko', eng: 'Hawk and Rooster',
        words: [{w: 'Phakwe', g: 'hawk'}, {w: 'le', g: 'and'}, {w: 'Mokoko', g: 'rooster'}],
        src: ['zerwick-story-af-2026'], note: ''},
       {tsw: 'e ne e le', eng: '(they) were',
        words: [{w: 'e', g: 'they / it: the class 9/10 concord (animals)'}, {w: 'ne', g: 'past marker'}, {w: 'e le', g: 'be (was / were)'}],
        src: ['zerwick-story-af-2026', 'autshumato', 'app'], note: 'Autshumato: \'e ne e le khamphani\' = \'it was a company\'. Same \'ne\' as the app\'s Ke ne ke batla, here with the animal-class concord e'},
       {tsw: 'ditsala', eng: 'friends',
        words: [{w: 'ditsala', g: 'friends (tsala > ditsala)'}],
        src: ['zerwick-story-af-2026', 'autshumato'], note: 'Autshumato: \'Ga se ditsala tsa gago\' = \'They are not your friends\''},
       {tsw: 'tse dikgolo', eng: 'great (big) ones',
        words: [{w: 'tse', g: 'which are: class 10 link'}, {w: 'dikgolo', g: 'big (di- + -golo > kgolo)'}],
        src: ['zerwick-story-af-2026', 'smart-guide-2026', 'autshumato'], note: 'Smart Guide: -golo > kgolo; his Afrikaans says \'goeie vriende\' (good friends)'},
     ]},
    {id: 'a1s-02', tsw: 'Phakwe o ne a tsamaya le Mokoko fa ba ya go sela tsie.',
     eng: 'Hawk used to go along with Rooster when they went to pick up locusts.',
     af: 'Valk het altyd saam met Hoenderhaan gaan sprinkane optel.',
     src: ['zerwick-ass1-2026', 'zerwick-story-af-2026'], audio: 'items/a1s-02.mp3', audio2: 'items/a1s-02-v2.mp3', note: '',
     chunks: [
       {tsw: 'Phakwe', eng: 'Hawk',
        words: [{w: 'Phakwe', g: 'hawk'}],
        src: ['zerwick-story-af-2026'], note: ''},
       {tsw: 'o ne a tsamaya', eng: 'used to go / was going',
        words: [{w: 'o', g: 'he: class 1 concord'}, {w: 'ne', g: 'past marker'}, {w: 'a', g: 'he (the concord shifts o > a after ne)'}, {w: 'tsamaya', g: 'go, walk'}],
        src: ['zerwick-story-af-2026', 'app', 'smart-guide-2026', 'pc'], note: 'same shape as the app\'s u3l2-03 \'O ne a batla\'. The story now treats Hawk as a person (o / a) where sentence 1 used the animal concord e; the Smart Guide\'s Khudu story does the same (\'Khudu o ne a itumela\')'},
       {tsw: 'le Mokoko', eng: 'with Rooster',
        words: [{w: 'le', g: 'with'}, {w: 'Mokoko', g: 'rooster'}],
        src: ['zerwick-story-af-2026', 'pc'], note: ''},
       {tsw: 'fa', eng: 'when',
        words: [{w: 'fa', g: 'when / while / if (a joiner). Not the verb fa = give (Peace Corps \'fa / file = Give\'): same spelling, different job'}],
        src: ['zerwick-story-af-2026'], note: 'his Afrikaans renders it \'as\' (when) in sentence 7 and \'terwyl\' (while) in sentence 3'},
       {tsw: 'ba ya', eng: 'they go',
        words: [{w: 'ba', g: 'they: class 2 concord'}, {w: 'ya', g: 'go'}],
        src: ['zerwick-story-af-2026', 'app'], note: 'app: Ke tla ya kwa sekolong'},
       {tsw: 'go sela', eng: 'to pick up',
        words: [{w: 'go', g: 'to (infinitive)'}, {w: 'sela', g: 'pick up, gather'}],
        src: ['zerwick-story-af-2026', 'pc'], note: 'Peace Corps: sela / setse = pick up; his Afrikaans: optel'},
       {tsw: 'tsie', eng: 'locusts',
        words: [{w: 'tsie', g: 'locust(s): same form singular and plural'}],
        src: ['zerwick-ass1-2026', 'zerwick-story-af-2026'], note: 'his gloss in the word list: locust / springkaan'},
     ]},
    {id: 'a1s-03', tsw: 'Ka letsatsi le lengwe fa ba ntse ba bua ka serame sa mariga,',
     eng: 'One day, while they were talking about the cold of winter,',
     af: 'Op \'n dag terwyl hulle praat oor die koue van die winter',
     src: ['zerwick-ass1-2026', 'zerwick-story-af-2026'], audio: 'items/a1s-03.mp3', audio2: 'items/a1s-03-v2.mp3', note: '',
     chunks: [
       {tsw: 'Ka letsatsi le lengwe', eng: 'one day',
        words: [{w: 'ka', g: 'on / by'}, {w: 'letsatsi', g: 'day (also: sun)'}, {w: 'le lengwe', g: 'one / a certain (class 5 agreement: le + -ngwe)'}],
        src: ['zerwick-story-af-2026', 'pc', 'smart-guide-2026', 'autshumato'], note: 'Smart Guide: \'leoto le lengwe\' = one leg; Autshumato: \'letsatsi le lengwe\' = another day'},
       {tsw: 'fa ba ntse ba bua', eng: 'while they were talking',
        words: [{w: 'fa', g: 'while'}, {w: 'ba', g: 'they'}, {w: 'ntse', g: 'being / still (continuing)'}, {w: 'ba', g: 'they'}, {w: 'bua', g: 'speak, talk'}],
        src: ['zerwick-story-af-2026', 'pc', 'app'], note: 'Peace Corps: nna / ntse = be; app: go bua = to speak, \'e santse e opa\' = still aches'},
       {tsw: 'ka serame', eng: 'about the cold',
        words: [{w: 'ka', g: 'about / with'}, {w: 'serame', g: 'cold (noun)'}],
        src: ['zerwick-story-af-2026', 'pc', 'afwn'], note: 'Peace Corps weather: \'go serame\' = it is cold'},
       {tsw: 'sa mariga', eng: 'of winter',
        words: [{w: 'sa', g: 'of: class 7 link (serame is se-/di-)'}, {w: 'mariga', g: 'winter'}],
        src: ['zerwick-story-af-2026', 'pc', 'autshumato'], note: 'Autshumato: \'serame sa mariga\' = \'winter cold\''},
     ]},
    {id: 'a1s-04', tsw: 'Phakwe ene a raya Mokoko a re:',
     eng: 'Hawk said to Rooster:',
     af: 'sê Valk vir Hoenderhaan:',
     src: ['zerwick-ass1-2026', 'zerwick-story-af-2026'], audio: 'items/a1s-04.mp3', audio2: 'items/a1s-04-v2.mp3', note: '',
     chunks: [
       {tsw: 'Phakwe ene', eng: 'Hawk, he',
        words: [{w: 'Phakwe', g: 'hawk'}, {w: 'ene', g: 'he / she (emphatic)'}],
        src: ['zerwick-story-af-2026', 'app'], note: 'app u1l4-03 ene'},
       {tsw: 'a raya Mokoko', eng: 'said to Rooster',
        words: [{w: 'a', g: 'he'}, {w: 'raya', g: 'say to, tell'}, {w: 'Mokoko', g: 'rooster'}],
        src: ['zerwick-story-af-2026', 'pc', 'smart-guide-2026'], note: 'Peace Corps: raya / reile = say; Smart Guide: \'Kgabo o ne o mo raya a re\''},
       {tsw: 'a re:', eng: 'saying:',
        words: [{w: 'a', g: 'he'}, {w: 're', g: 'say'}],
        src: ['zerwick-story-af-2026', 'smart-guide-2026', 'afwn'], note: 'the quote-opener; Smart Guide: \'O ne a re, "Ke a leboga"\''},
     ]},
    {id: 'a1s-05', tsw: 'Nna ke na le lemao mme ke tla rokela bana ba me dikobo.',
     eng: '"I have a needle and I will sew blankets for my children".',
     af: '"Ek het \'n naald en ek sal vir my kinders komberse maak".',
     src: ['zerwick-ass1-2026', 'zerwick-story-af-2026'], audio: 'items/a1s-05.mp3', audio2: 'items/a1s-05-v2.mp3', note: '',
     chunks: [
       {tsw: 'Nna', eng: 'I / as for me',
        words: [{w: 'nna', g: 'I, me (emphatic)'}],
        src: ['zerwick-story-af-2026', 'app'], note: 'app u1l4-01'},
       {tsw: 'ke na le', eng: 'I have',
        words: [{w: 'ke', g: 'I'}, {w: 'na le', g: 'have'}],
        src: ['zerwick-story-af-2026', 'app'], note: 'app u1l4-10 Ke na le buka'},
       {tsw: 'lemao', eng: 'a needle',
        words: [{w: 'lemao', g: 'needle'}],
        src: ['zerwick-story-af-2026'], note: 'his Afrikaans: naald'},
       {tsw: 'mme', eng: 'and (then) / but',
        words: [{w: 'mme', g: 'but; and then'}],
        src: ['zerwick-story-af-2026', 'app', 'pc'], note: 'app u4l5-03 mme = but; his Afrikaans uses \'en\' here'},
       {tsw: 'ke tla rokela', eng: 'I will sew (for)',
        words: [{w: 'ke', g: 'I'}, {w: 'tla', g: 'will'}, {w: 'rokela', g: 'sew for (roka = sew, -ela = for someone)'}],
        src: ['zerwick-story-af-2026', 'app', 'afwn'], note: 'app: Ke tla batla; dictionary: roka = sew'},
       {tsw: 'bana ba me', eng: 'my children',
        words: [{w: 'bana', g: 'children'}, {w: 'ba me', g: 'my (class 2 link + me)'}],
        src: ['zerwick-story-af-2026', 'app'], note: 'app u2l4-08 bana; same \'me\' as the intro line \'Leina la me\''},
       {tsw: 'dikobo', eng: 'blankets',
        words: [{w: 'dikobo', g: 'blankets (kobo > dikobo)'}],
        src: ['zerwick-story-af-2026', 'pc'], note: 'Peace Corps: kobo = blanket'},
     ]},
    {id: 'a1s-06', tsw: 'Mokoko wa re:',
     eng: 'Rooster said:',
     af: 'Hoenderhaan sê toe:',
     src: ['zerwick-ass1-2026', 'zerwick-story-af-2026'], audio: 'items/a1s-06.mp3', audio2: 'items/a1s-06-v2.mp3', note: '',
     chunks: [
       {tsw: 'Mokoko wa re:', eng: 'Rooster said:',
        words: [{w: 'Mokoko', g: 'rooster'}, {w: 'wa re', g: 'said (narrative \'said\', class 1)'}],
        src: ['zerwick-story-af-2026'], note: 'his Afrikaans: \'sê toe\''},
     ]},
    {id: 'a1s-07', tsw: 'Nna ga ke na lemao, ke tla adima la gago fa o feditse.',
     eng: '"I don\'t have a needle, I will borrow yours when you have finished".',
     af: '"Ek het nie \'n naald nie maar ek sal joune leen as jy klaar is".',
     src: ['zerwick-ass1-2026', 'zerwick-story-af-2026'], audio: 'items/a1s-07.mp3', audio2: 'items/a1s-07-v2.mp3', note: '',
     chunks: [
       {tsw: 'Nna', eng: 'I / as for me',
        words: [{w: 'nna', g: 'I, me'}],
        src: ['zerwick-story-af-2026', 'app'], note: ''},
       {tsw: 'ga ke na lemao', eng: 'I don\'t have a needle',
        words: [{w: 'ga', g: 'not'}, {w: 'ke', g: 'I'}, {w: 'na', g: 'have'}, {w: 'lemao', g: 'needle'}],
        src: ['zerwick-story-af-2026', 'app'], note: 'app u1l7-06 \'ga ke na mathata\'; the negative of ke na le drops the le'},
       {tsw: 'ke tla adima', eng: 'I will borrow',
        words: [{w: 'ke', g: 'I'}, {w: 'tla', g: 'will'}, {w: 'adima', g: 'borrow (also lend)'}],
        src: ['zerwick-story-af-2026', 'pc', 'autshumato'], note: 'Peace Corps: adima / adimile = borrow'},
       {tsw: 'la gago', eng: 'yours',
        words: [{w: 'la', g: 'of: class 5 link (lemao is le-)'}, {w: 'gago', g: 'you (possessor)'}],
        src: ['zerwick-story-af-2026', 'app'], note: 'same la gago as \'Leina la gago\''},
       {tsw: 'fa o feditse', eng: 'when you have finished',
        words: [{w: 'fa', g: 'when'}, {w: 'o', g: 'you'}, {w: 'feditse', g: 'have finished (fetsa > feditse)'}],
        src: ['zerwick-story-af-2026', 'pc', 'smart-guide-2026'], note: 'Smart Guide: -tsa > -ditse: fetsa > feditse; his Afrikaans: \'as jy klaar is\''},
     ]},
  ],

  /* 7 phrases cut out of the story as drill cards. This is her SECOND set: she practised
     against the first eight (2026-09-11) and on 2026-09-12 picked the seven pieces she
     actually kept stumbling over, so the old p03/p04/p05/p07/p08 are gone and four of
     these are new lines. Every string is copied verbatim out of toolkit/ass1-mapping-v2.json.
     ⚠️ AUDIO. The three whose text did NOT change (p01, p02, p06) keep their v1 clip.
     The four NEW ones carry `audio2` only: the v1 mp3 sitting at that filename says the
     OLD phrase, so wiring it here would play a learner something other than what the
     card shows. In V1 they fall back to the second speaker — right voice or not, it is
     at least the right words. */
  phrases: [
    {id: 'a1s-p01', tsw: 'Ga twe bogologolo', eng: 'it is said (that) long ago', af: 'daar word vertel dat ... lank gelede', src: ['zerwick-story-af-2026', 'autshumato', 'smart-guide-2026'], audio: 'items/a1s-p01.mp3', audio2: 'items/a1s-p01-v2.mp3',
     note: 'Her slice, ear-checked 2026-09-12.'},
    {id: 'a1s-p02', tsw: 'fa ba ya go sela tsie', eng: 'when they go to pick up locusts', af: 'as hulle sprinkane gaan optel', src: ['zerwick-story-af-2026', 'pc'], audio: 'items/a1s-p02.mp3', audio2: 'items/a1s-p02-v2.mp3',
     note: 'Her slice, ear-checked 2026-09-12.'},
    {id: 'a1s-p03', tsw: 'e ne e le ditsala', eng: '(they) were friends', af: 'was vriende', src: ['zerwick-story-af-2026', 'autshumato', 'app'], audio2: 'items/a1s-p03-v2.mp3',
     note: 'e = they (the animal-class concord); ne = past marker; e le = be (was / were); ditsala = friends (tsala > ditsala). Her slice, ear-checked 2026-09-12.'},
    {id: 'a1s-p04', tsw: 'Ka letsatsi le lengwe', eng: 'one day', af: 'op \'n dag', src: ['zerwick-story-af-2026', 'pc', 'smart-guide-2026', 'autshumato'], audio2: 'items/a1s-p04-v2.mp3',
     note: 'ka = on / by; letsatsi = day (also: sun); le lengwe = one / a certain (class 5 agreement); Smart Guide: \'leoto le lengwe\' = one leg. Her slice, ear-checked 2026-09-12.'},
    {id: 'a1s-p05', tsw: 'fa ba ntse', eng: 'while they were (still) ...', af: 'terwyl hulle (nog) ...', src: ['zerwick-story-af-2026', 'pc', 'app'], audio2: 'items/a1s-p05-v2.mp3',
     note: 'fa = while; ba = they; ntse = being / still (continuing). The start of \'fa ba ntse ba bua\'; ba bua = they speak completes it. Her slice, ear-checked 2026-09-12.'},
    {id: 'a1s-p06', tsw: 'Nna ke na le lemao', eng: 'As for me, I have a needle', af: 'Ek het \'n naald', src: ['zerwick-story-af-2026', 'app'], audio: 'items/a1s-p06.mp3', audio2: 'items/a1s-p06-v2.mp3',
     note: 'Her slice, ear-checked 2026-09-12.'},
    {id: 'a1s-p07', tsw: 'Nna ga ke na lemao', eng: 'As for me, I don\'t have a needle', af: 'Ek het nie \'n naald nie', src: ['zerwick-story-af-2026', 'app'], audio2: 'items/a1s-p07-v2.mp3',
     note: 'nna = I (emphatic); ga ke na = I don\'t have (the negative of ke na le drops the le; app u1l7-06 \'ga ke na mathata\'); lemao = needle. Her slice, ear-checked 2026-09-12.'},
  ],

  /* The whole tape, read straight through. Same {audio, audio2} shape as a card, so the
     tab's one audio resolver handles these too. `slow` exists in both voices. `nat` is
     the natural-pace read-through: it exists ONLY on the second speaker's tape — the
     first speaker's tape holds the slow reading and nothing else (her ruling
     2026-09-11), so `nat` carries no v1 file and never will. */
  whole: {
    slow: {audio: 'items/a1s-slow.mp3', audio2: 'items/a1s-slow-v2.mp3'},
    nat: {audio2: 'items/a1s-nat-v2.mp3'}
  }
};
