// Re:Lefela — 🔊 Medumo word sets. GENERATED FILE — do not hand-edit.
// Rebuild: python toolkit/medumo-build.py && python toolkit/verify-medumo-bank.py
//
// Source: "1 Sound values of Setswana 121-521 2024" (Johan Zerwick, SECL121).
// Glosses are his, copied verbatim — never improved or re-translated. Words the
// app can corroborate from an open source carry that source too (afwn = African
// Wordnet, auts = Autshumato). The handout itself stays in gitignored corpus/.
//
// Sets follow the handout's own order: one sound, the words that demonstrate it.
// 33 sets, 164 words.
const RL_MEDUMO = [
  {"id": "md01", "label": "a · ê", "words": [{"e": "love / like", "k": 1, "src": ["zerwick-2024", "afwn", "pc", "wikt"], "t": "rata"}, {"e": "kick", "src": ["zerwick-2024"], "t": "raga"}, {"e": "green", "src": ["zerwick-2024", "afwn"], "t": "tala"}, {"e": "search / want", "k": 1, "src": ["zerwick-2024", "afwn", "pc"], "t": "batla"}, {"e": "buy", "k": 1, "src": ["zerwick-2024", "pc", "wikt"], "t": "rêka"}]},
  {"id": "md02", "label": "ê · ô", "words": [{"e": "chop", "src": ["zerwick-2024"], "t": "rêma"}, {"e": "chase", "src": ["zerwick-2024", "afwn"], "t": "lêlêka"}, {"e": "gossip", "src": ["zerwick-2024", "afwn"], "t": "sêba"}, {"e": "stand / wait", "k": 1, "src": ["zerwick-2024", "afwn", "wikt"], "t": "êma"}, {"e": "punish", "src": ["zerwick-2024", "afwn", "wikt"], "t": "ôtla"}]},
  {"id": "md03", "label": "ô · o", "words": [{"e": "peel", "src": ["zerwick-2024", "afwn"], "t": "ôbola"}, {"e": "sit at the fire", "src": ["zerwick-2024", "afwn"], "t": "ôra"}, {"e": "break", "src": ["zerwick-2024", "afwn"], "t": "rôba"}, {"e": "personal name / answer", "src": ["zerwick-2024", "afwn"], "t": "Karabô"}, {"e": "bite", "src": ["zerwick-2024", "afwn", "wikt"], "t": "loma"}]},
  {"id": "md04", "label": "o · e", "words": [{"e": "you", "k": 1, "src": ["zerwick-2024"], "t": "lona"}, {"e": "we", "k": 1, "src": ["zerwick-2024", "wikt"], "t": "rona"}, {"e": "plough", "src": ["zerwick-2024", "afwn", "wikt"], "t": "lema"}, {"e": "try", "src": ["zerwick-2024", "afwn", "pc"], "t": "leka"}, {"e": "cry", "src": ["zerwick-2024", "afwn", "pc"], "t": "lela"}]},
  {"id": "md05", "label": "e · u", "words": [{"e": "cut", "src": ["zerwick-2024", "afwn", "wikt"], "t": "sega"}, {"e": "break / destroy", "src": ["zerwick-2024", "afwn", "pc", "wikt"], "t": "senya"}, {"e": "a thing", "src": ["zerwick-2024", "afwn"], "t": "selô"}, {"e": "swell", "src": ["zerwick-2024", "afwn"], "t": "ruruga"}, {"e": "hear", "src": ["zerwick-2024", "afwn", "pc", "wikt"], "t": "utlwa"}]},
  {"id": "md06", "label": "u · i", "words": [{"e": "hour", "src": ["zerwick-2024", "afwn"], "t": "ura"}, {"e": "steal", "src": ["zerwick-2024", "afwn"], "t": "utswa"}, {"e": "labourer", "k": 1, "src": ["zerwick-2024", "afwn"], "t": "modiri"}, {"e": "reverend", "k": 1, "src": ["zerwick-2024", "afwn"], "t": "moruti"}, {"e": "know", "k": 1, "src": ["zerwick-2024", "afwn", "pc"], "t": "itse"}]},
  {"id": "md07", "label": "i · a · e · ê", "words": [{"e": "strike / hit", "src": ["zerwick-2024", "afwn"], "t": "itaya"}, {"e": "build", "src": ["zerwick-2024", "afwn", "wikt"], "t": "aga"}, {"e": "answer", "src": ["zerwick-2024", "afwn", "pc", "wikt"], "t": "araba"}, {"e": "horn", "src": ["zerwick-2024", "afwn"], "t": "lenaka"}, {"e": "church", "src": ["zerwick-2024", "afwn", "pc"], "t": "kêrêkê"}]},
  {"id": "md08", "label": "i · ô · o · u", "words": [{"e": "wolf", "k": 1, "src": ["zerwick-2024", "afwn", "wikt"], "t": "phiri"}, {"e": "wild animal", "k": 1, "src": ["zerwick-2024", "afwn", "wikt"], "t": "phôlôgôlô"}, {"e": "town", "src": ["zerwick-2024", "afwn", "wikt"], "t": "tôrôpô"}, {"e": "human", "k": 1, "src": ["zerwick-2024", "afwn", "wikt"], "t": "motho"}, {"e": "tortoise", "src": ["zerwick-2024", "wikt"], "t": "khudu"}]},
  {"id": "md09", "label": "u · b", "words": [{"e": "blue", "src": ["zerwick-2024", "afwn"], "t": "pududu"}, {"e": "read", "k": 1, "src": ["zerwick-2024", "afwn", "wikt"], "t": "bala"}, {"e": "speak", "k": 1, "src": ["zerwick-2024", "afwn", "pc", "wikt"], "t": "bua"}, {"e": "call", "src": ["zerwick-2024", "afwn", "pc", "wikt"], "t": "bitsa"}, {"e": "ask", "src": ["zerwick-2024", "afwn", "pc", "wikt"], "t": "botsa"}]},
  {"id": "md10", "label": "d", "words": [{"e": "wells/draw-wells/pits", "src": ["zerwick-2024"], "t": "didiba"}, {"e": "do / work", "k": 1, "src": ["zerwick-2024", "afwn", "pc"], "t": "dira"}, {"e": "books", "src": ["zerwick-2024"], "t": "dibuka"}, {"e": "pay", "src": ["zerwick-2024", "afwn", "pc"], "t": "duêla"}, {"e": "greet", "src": ["zerwick-2024", "afwn", "pc"], "t": "dumedisa"}]},
  {"id": "md11", "label": "f", "words": [{"e": "blind", "src": ["zerwick-2024"], "t": "sefôfu"}, {"e": "give", "src": ["zerwick-2024", "afwn", "pc"], "t": "fa"}, {"e": "hide / conceal", "src": ["zerwick-2024", "afwn", "pc"], "t": "fitlha"}, {"e": "finish", "src": ["zerwick-2024", "afwn", "pc"], "t": "fetsa"}, {"e": "cheat / deceive", "src": ["zerwick-2024"], "t": "fora"}]},
  {"id": "md12", "label": "g · h", "words": [{"e": "refuse / deny", "src": ["zerwick-2024", "afwn", "pc"], "t": "gana"}, {"e": "milk - verb", "src": ["zerwick-2024"], "t": "gama"}, {"e": "today", "k": 1, "src": ["zerwick-2024", "afwn", "pc"], "t": "gômpiênô"}, {"e": "again", "src": ["zerwick-2024", "pc"], "t": "gapê"}, {"e": "become rich", "src": ["zerwick-2024", "wikt"], "t": "huma"}]},
  {"id": "md13", "label": "h · j", "words": [{"e": "hat", "src": ["zerwick-2024"], "t": "hutse"}, {"e": "rake", "src": ["zerwick-2024"], "t": "haraka"}, {"e": "sow / plant", "src": ["zerwick-2024", "afwn"], "t": "jala"}, {"e": "eat", "k": 1, "src": ["zerwick-2024", "afwn", "pc", "wikt"], "t": "ja"}, {"e": "so", "k": 1, "src": ["zerwick-2024"], "t": "jalo"}]},
  {"id": "md14", "label": "j · k", "words": [{"e": "now", "k": 1, "src": ["zerwick-2024", "afwn"], "t": "jaanong"}, {"e": "how", "k": 1, "src": ["zerwick-2024"], "t": "jang"}, {"e": "tree trunk", "src": ["zerwick-2024"], "t": "kutu"}, {"e": "branch", "src": ["zerwick-2024", "afwn"], "t": "kala"}, {"e": "vehicle / wagon", "src": ["zerwick-2024", "afwn", "wikt"], "t": "koloi"}]},
  {"id": "md15", "label": "l · m", "words": [{"e": "dream", "src": ["zerwick-2024"], "t": "lôra"}, {"e": "look", "src": ["zerwick-2024", "afwn", "pc"], "t": "leba"}, {"e": "arm", "src": ["zerwick-2024", "afwn"], "t": "lebôgô"}, {"e": "young man", "src": ["zerwick-2024", "afwn"], "t": "lekau"}, {"e": "fold", "src": ["zerwick-2024", "afwn"], "t": "mena"}]},
  {"id": "md16", "label": "m · n", "words": [{"e": "man", "src": ["zerwick-2024", "afwn", "wikt"], "t": "monna"}, {"e": "meat", "k": 1, "src": ["zerwick-2024", "afwn", "wikt"], "t": "nama"}, {"e": "number", "src": ["zerwick-2024"], "t": "nômôrô"}, {"e": "calf", "src": ["zerwick-2024", "afwn", "wikt"], "t": "namane"}, {"e": "star", "src": ["zerwick-2024", "afwn"], "t": "nalêdi"}]},
  {"id": "md17", "label": "p", "words": [{"e": "win / get the better of / master", "src": ["zerwick-2024", "afwn"], "t": "palêla"}, {"e": "pot", "src": ["zerwick-2024", "afwn", "wikt"], "t": "pitsa"}, {"e": "meeting", "src": ["zerwick-2024", "afwn"], "t": "pitsô"}, {"e": "question", "src": ["zerwick-2024", "afwn", "wikt"], "t": "potsô"}, {"e": "paper", "src": ["zerwick-2024", "afwn", "wikt"], "t": "pampiri"}]},
  {"id": "md18", "label": "r · s", "words": [{"e": "send", "k": 1, "src": ["zerwick-2024", "afwn"], "t": "roma"}, {"e": "sew together – with needle and thread", "src": ["zerwick-2024", "afwn"], "t": "roka"}, {"e": "school", "k": 1, "src": ["zerwick-2024", "afwn", "pc"], "t": "sekôlô"}, {"e": "tree", "src": ["zerwick-2024", "afwn", "wikt"], "t": "setlharê"}, {"e": "summer", "src": ["zerwick-2024", "afwn", "pc", "wikt"], "t": "selemô"}]},
  {"id": "md19", "label": "š · t", "words": [{"e": "milk", "src": ["zerwick-2024", "afwn"], "t": "mašwi"}, {"e": "flowers", "src": ["zerwick-2024"], "t": "dišeše"}, {"e": "run", "src": ["zerwick-2024", "afwn"], "t": "taboga"}, {"e": "lion", "k": 1, "src": ["zerwick-2024", "afwn", "wikt"], "t": "tau"}, {"e": "dam", "src": ["zerwick-2024"], "t": "tamô"}]},
  {"id": "md20", "label": "t · w · kg", "words": [{"e": "train", "src": ["zerwick-2024", "afwn"], "t": "terena"}, {"e": "you", "k": 1, "src": ["zerwick-2024"], "t": "wena"}, {"e": "are killed", "src": ["zerwick-2024"], "t": "bolawa"}, {"e": "reprimand / rebuke / reprove", "src": ["zerwick-2024", "afwn"], "t": "kgalema"}, {"e": "pail", "src": ["zerwick-2024", "afwn"], "t": "kgamêlô"}]},
  {"id": "md21", "label": "kg · ng", "words": [{"e": "push", "src": ["zerwick-2024", "afwn"], "t": "kgôrômêtsa"}, {"e": "doctor", "k": 1, "src": ["zerwick-2024", "afwn", "wikt"], "t": "ngaka"}, {"e": "scratch me", "src": ["zerwick-2024"], "t": "nngapa"}, {"e": "throw", "src": ["zerwick-2024", "afwn"], "t": "ngata"}, {"e": "become vexed or annoyed", "src": ["zerwick-2024", "afwn"], "t": "ngôngôrêga"}]},
  {"id": "md22", "label": "ny · tl", "words": [{"e": "marry", "src": ["zerwick-2024", "wikt"], "t": "nyala"}, {"e": "disappear", "src": ["zerwick-2024"], "t": "nyamêla"}, {"e": "come", "k": 1, "src": ["zerwick-2024", "afwn", "pc", "wikt"], "t": "tla"}, {"e": "jump", "src": ["zerwick-2024", "afwn", "wikt"], "t": "tlola"}, {"e": "bring", "src": ["zerwick-2024", "afwn", "pc"], "t": "tlisa"}]},
  {"id": "md23", "label": "tl · ts", "words": [{"e": "fill up", "src": ["zerwick-2024", "afwn", "wikt"], "t": "tlatsa"}, {"e": "rise", "k": 1, "src": ["zerwick-2024", "afwn", "pc", "wikt"], "t": "tsoga"}, {"e": "hunt", "src": ["zerwick-2024", "afwn", "wikt"], "t": "tsoma"}, {"e": "walk", "src": ["zerwick-2024", "afwn", "pc", "wikt"], "t": "tsamaya"}, {"e": "cold", "src": ["zerwick-2024", "afwn"], "t": "tsididi"}]},
  {"id": "md24", "label": "kh · ph", "words": [{"e": "kneel", "src": ["zerwick-2024", "afwn"], "t": "khubama"}, {"e": "apron", "src": ["zerwick-2024", "afwn"], "t": "khiba"}, {"e": "cover / lid / flap / top / cap", "src": ["zerwick-2024", "afwn"], "t": "sekhurumêlô"}, {"e": "dust / polish", "src": ["zerwick-2024", "afwn"], "t": "phimola"}, {"e": "grab", "src": ["zerwick-2024", "afwn"], "t": "phamola"}]},
  {"id": "md25", "label": "ph · th", "words": [{"e": "set – the sun", "src": ["zerwick-2024", "afwn"], "t": "phirima"}, {"e": "west", "src": ["zerwick-2024"], "t": "bophirima"}, {"e": "mountain", "src": ["zerwick-2024", "afwn", "wikt"], "t": "thaba"}, {"e": "pip", "src": ["zerwick-2024", "afwn"], "t": "thapô"}, {"e": "oppose", "src": ["zerwick-2024", "afwn"], "t": "thiba"}]},
  {"id": "md26", "label": "th · tlh", "words": [{"e": "shoot / explode", "src": ["zerwick-2024", "afwn"], "t": "thunya"}, {"e": "hoe", "src": ["zerwick-2024"], "t": "tlhagola"}, {"e": "head", "k": 1, "src": ["zerwick-2024", "afwn"], "t": "tlhôgô"}, {"e": "understand / grasp", "src": ["zerwick-2024", "afwn", "pc"], "t": "tlhaloganya"}, {"e": "stab / slaughter", "src": ["zerwick-2024", "afwn"], "t": "tlhaba"}]},
  {"id": "md27", "label": "tlh · kg · ny · ph · th", "words": [{"e": "mix", "src": ["zerwick-2024", "afwn"], "t": "tlhakanya"}, {"e": "cow", "k": 1, "src": ["zerwick-2024", "afwn", "wikt"], "t": "kgomo"}, {"e": "marriage", "src": ["zerwick-2024", "afwn", "wikt"], "t": "lenyalo"}, {"e": "eland", "src": ["zerwick-2024", "wikt"], "t": "phofu"}, {"e": "hard", "k": 1, "src": ["zerwick-2024", "afwn"], "t": "thata"}]},
  {"id": "md28", "label": "tl · ts · šh", "words": [{"e": "full", "src": ["zerwick-2024", "afwn", "wikt"], "t": "tlala"}, {"e": "elephant", "src": ["zerwick-2024", "afwn", "wikt"], "t": "tlou"}, {"e": "ear", "k": 1, "src": ["zerwick-2024", "afwn", "wikt"], "t": "tsêbê"}, {"e": "village", "src": ["zerwick-2024", "afwn"], "t": "motse"}, {"e": "applause", "src": ["zerwick-2024"], "t": "lešhalaba"}]},
  {"id": "md29", "label": "tš · tlh · tsh", "words": [{"e": "acidity", "src": ["zerwick-2024", "afwn"], "t": "botšarara"}, {"e": "go up", "src": ["zerwick-2024", "afwn"], "t": "tlhatloga"}, {"e": "spark", "src": ["zerwick-2024", "afwn"], "t": "tlhase"}, {"e": "bell", "src": ["zerwick-2024", "afwn", "wikt"], "t": "tshipi"}, {"e": "courtcase", "src": ["zerwick-2024", "afwn"], "t": "tshêkô"}]},
  {"id": "md30", "label": "tšh · gw · hw · jw", "words": [{"e": "money", "src": ["zerwick-2024", "afwn"], "t": "tšhelete"}, {"e": "fine stamped meat", "src": ["zerwick-2024"], "t": "tšhotlho"}, {"e": "his/hers", "k": 1, "src": ["zerwick-2024"], "t": "gagwe"}, {"e": "red", "src": ["zerwick-2024"], "t": "hwibidu"}, {"e": "to plant", "src": ["zerwick-2024", "afwn", "wikt"], "t": "jwala"}]},
  {"id": "md31", "label": "kw · lw · nw · ngw · rw", "words": [{"e": "write", "src": ["zerwick-2024", "afwn", "pc", "wikt"], "t": "kwala"}, {"e": "to be ill", "k": 1, "src": ["zerwick-2024", "afwn", "pc"], "t": "lwala"}, {"e": "drink", "k": 1, "src": ["zerwick-2024", "afwn", "pc", "wikt"], "t": "nwa"}, {"e": "child", "src": ["zerwick-2024", "afwn", "pc", "wikt"], "t": "ngwana"}, {"e": "wear", "src": ["zerwick-2024", "afwn", "wikt"], "t": "rwala"}]},
  {"id": "md32", "label": "sw · tsw · tšw · tw · kgw", "words": [{"e": "die", "src": ["zerwick-2024", "afwn", "wikt"], "t": "swa"}, {"e": "to exit", "k": 1, "src": ["zerwick-2024", "afwn", "pc", "wikt"], "t": "tswa"}, {"e": "to be trusted", "src": ["zerwick-2024"], "t": "tshetšwa"}, {"e": "to make a bang sound as with a whip", "src": ["zerwick-2024"], "t": "twanya"}, {"e": "drive", "src": ["zerwick-2024", "afwn"], "t": "kgweetsa"}]},
  {"id": "md33", "label": "thw · tlhw · tshw · tšhw", "words": [{"e": "transport", "src": ["zerwick-2024", "wikt"], "t": "thwala"}, {"e": "price/value", "src": ["zerwick-2024", "afwn"], "t": "tlhwatlhwa"}, {"e": "mark", "src": ["zerwick-2024", "afwn"], "t": "tshwaya"}, {"e": "erase", "src": ["zerwick-2024", "afwn"], "t": "tšhwimola"}]}
];

// Minimal pairs — the circumflex changes which word it is. Drilled as their own
// round at the end of the tab (her ask, 2026-09-01).
const RL_MEDUMO_PAIRS = [
  {"ask": "mother", "id": "mp1", "note": "The app teaches mme = \"but\" (u4l5-03). With the hat it is a different word entirely — mmê, mother. Same three letters, nothing else shared.", "opts": [{"e": "mother", "src": ["zerwick-2024"], "t": "mmê"}, {"e": "but", "src": ["peace-corps-L9"], "t": "mme"}]},
  {"ask": "this one (this man)", "id": "mp2", "note": "Plain yo is the joining word \"who\" — Ke Modisa yo o Molemo, \"the shepherd WHO is good\" (u5l4-05). Hatted yô points at someone: this one, this man.", "opts": [{"e": "this one (this man)", "src": ["zerwick-2024"], "t": "yô"}, {"e": "who (the one that…)", "src": ["beibele"], "t": "yo"}]},
  {"ask": "healing, cooling", "id": "mp3", "note": "His three-way example, and the sharpest one in the handout: one hat moved gives you an ox, healing, or a harvest.", "opts": [{"e": "healing, cooling", "src": ["zerwick-2024"], "t": "phôlô"}, {"e": "ox", "src": ["zerwick-2024"], "t": "pholo"}, {"e": "harvest", "src": ["zerwick-2024"], "t": "pholô"}]},
  {"ask": "hip / pelvis", "id": "mp4", "note": "noka is a river; nôka is your hip.", "opts": [{"e": "hip / pelvis", "src": ["zerwick-2024"], "t": "nôka"}, {"e": "river", "src": ["zerwick-2024"], "t": "noka"}]},
  {"ask": "pour", "id": "mp5", "note": "tshela = live, tshêla = pour.", "opts": [{"e": "pour", "src": ["zerwick-2024"], "t": "tshêla"}, {"e": "live", "src": ["zerwick-2024"], "t": "tshela"}]},
  {"ask": "develop a habit / grow horns", "id": "mp6", "note": "lema is to plough — the everyday one. lêma is to grow horns, or to pick up a habit.", "opts": [{"e": "develop a habit / grow horns", "src": ["zerwick-2024"], "t": "lêma"}, {"e": "plough", "src": ["zerwick-2024"], "t": "lema"}]},
  {"ask": "stop street", "id": "mp7", "note": "Worth getting right: setopo is a corpse, setôpô is a stop street.", "opts": [{"e": "stop street", "src": ["zerwick-2024"], "t": "setôpô"}, {"e": "corpse", "src": ["zerwick-2024"], "t": "setopo"}]}
];
